### ISSUE TITLE
Unable to start arweave because econrefused

### ISSUE THREAD

**Issue by cluutch** [salt-labs/arweave-miner#11]
Arweave non-responsive after starting Docker container with `docker run -e ARWEAVE_REWARD_ADDRESS="XYZ" -p 1984:1984 IMAGE_SHA`.

```
# From docker container
$ cat /arweave/log/erlang.log.1

...
Root: /arweave
/arweave
Protocol 'inet_tcp': register/listen error: econnrefused
```

The docker process seems [stuck initiating Arweave](https://github.com/salt-labs/arweave-miner/blob/f29c5a680279bbc3a11c2d04b2a4460ec7621f30/scripts/entrypoint.sh#L232). `curl localhost:1984/info` fails from both the host and container.

**Comment by cluutch** [comment]
Adding host networking to the container solves the problem. 

```
version: "3.9"
services:
  arweave:
    image: "ghcr.io/cluutch/arweave-miner:latest"
    environment:
      - ARWEAVE_REWARD_ADDRESS=XYZ
    network_mode: "host"
```
